# Generated by Django 4.0.6 on 2023-06-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
